# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: format-checker
        name: formatting
        language: system
        entry: make format
  - repo: local
    hooks:
      - id: lint-checker
        name: linter run
        language: system
        entry: make lint
